### ISSUE TITLE
Add unit tests to the boilerplate using Jest/Enzyme

### ISSUE THREAD

**Issue by levsthings** [ShippableBoilerplates/react-spa-clientside-cdn#1]
This is a React/Redux/Redux-Saga boilerplate for people to use and kickstart a project.

It has a placeholder welcome screen similar to `create-react-app` that showcases a Redux counter example and an example API call with Redux-Saga that fetches a random Chuck Norris joke. Unit tests need to be written for the components and Redux related exports to encourage users to use TDD. It should be fairly easy to get this project to 100% coverage.

**Comment by brascene** [comment]
Hi there, can I take this one? I'll start tonight if it's ok

**Comment by levsthings** [comment]
Absolutely, let me know if you have any questions.

**Comment by brascene** [comment]
Just to let u know, I'm working on this :D

**Comment by levsthings** [comment]
Thanks!

**Comment by frytyler** [comment]
@brascene are you still on this? I can help out if you need. I could get jest setup with enzyme that way there could be smaller issues created for specific test suits. 

@levsthings would that work for you? Im also wondering if you would like [prettier](https://github.com/prettier/prettier) installed to format according to your eslint rules

**Comment by frytyler** [comment]
@brascene @levsthings sorry I didn't see the PR I'm still up for helping if needed but carry on

**Comment by levsthings** [comment]
Hey @frytyler! There's still work to be done on @brascene's PR, but there's no on-going work there so feel free to takeover that PR or make your own.

Using `prettier` is also a very good idea, especially if you could make it play well with the current `eslint` setup.

**Comment by levsthings** [comment]
I took care of the main tests today without the PR because I don't think we need mocking in this project. If anyone needs another PR for #Hacktoberfest, feel free to take #3.

**Comment by frytyler** [comment]
Sorry @levsthings got swamped with a few other things and haven't had time to jump on any oss

**Comment by levsthings** [comment]
No worries @frytyler, there's still plenty of until the month finishes. If someone else grabs the smaller unit test issue I mentioned (#3), you can even send a PR **only** implementing `prettier` as you've suggested earlier.
